import pandas as pd

# NOTE: as of now this is just some random code fragments migrated from
# the main script. Intent is to extract only the data points we care about
# from the DataFrame generated by ALF run, and store them in a more friendly
# format. Need to refactor to include the stuff we want, and ideally vectorize
# it as well.

param_keys = ["t", "U", "mu", "beta", "dtau"]
observables = ["N", "E", "T", "V"]
obs_errs = ["d"+o for o in observables]
obs_signs = ["s"+o for o in observables]
obs_names = ["Part", "Ener", "Kin", "Pot"]

for o, do, so, o_name in zip(observables, obs_errs, obs_signs, obs_names):
    res[o].append(obs[o_name + "_scal0"])
    res[do].append(obs[o_name + "_scal0_err"])
    res[so].append(obs[o_name + "_scal_sign"])
res["t"].append(t)
res["U"].append(U)
res["mu"].append(mu)
res["dtau"].append(dtau)
res["beta"].append(beta)
