# in-depth mu sweep at low U
# original python code:
#    DTAUS = [0.04]
#    BETAS = [20]
#    TS = [1.0]
#    US = [-0.5, -1.0, -2.0]
#    MUS = [-1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.5]
#    PHI_VALS = np.linspace(0,1,17,endpoint=True).tolist()
#    Nsweep = 150
#    Nbin = 15
#    Lx = Ly = 4
#    Nf = 4

## loopable params
dtaus: 0.04
betas: 20
ts: 1.0
Us: [-0.5, -1.0, -2.0]
mus: [-1.0, -1.25, -1.5, -1.75, -2.0, -2.25, -2.5]
phis: linspace 0 1 17

## scalar params
Nsweep: 150
Nbin: 15
Lx: 4
Ly: 4
Nf: 4
