# 2-fermion check run for the original phi sweep
# original python code:
#    DTAUS = [0.02]
#    BETAS = [20]
#    TS = [1.0]
#    US = [-1.0]
#    MUS = [0.0, -1.0, -2.0]
#    PHI_VALS = np.linspace(0,1,21,endpoint=True).tolist()
#    Nsweep = 150
#    Nbin = 15
#    Lx = Ly = 4
#    Nf = 2

## loopable params
dtaus: 0.02
betas: 20
ts: 1.0
Us: -1.0
mus: [0.0, -1.0, -2.0]
phis: linspace 0 1 21

## scalar params
Nsweep: 150
Nbin: 15
Lx: 4
Ly: 4
Nf: 2
