# quick run for testing

## loopable params
dtaus: 0.1
betas: 1
ts: 1.0
Us: -1.0
mus: linspace -1.0 1.0 4
phis: linspace 0.0 1.0 5

## scalar params
Nsweep: 10
Nbin: 3
Lx: 4
Ly: 4
Nf: 4

## optional params (just to test that they work)
projector: True
theta: 30
